# Generated by Django 3.0 on 2021-02-22 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210220_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='duedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
